### ISSUE TITLE
Morning session code review W2D3

### ISSUE THREAD

**Issue by rachaouldbabaali** [Paul-tes/My-Portfolio#4]
This is feedback from Microverse morning session team :

-  The form looks good by applying inputs and max-length as requested.
- The code is of high quality.

**Comment by Nahid1911** [comment]
@Paul-tes good job so far 👌, 
as per the project requirement the label tag is unnecessary as the input field does not include any text outside the input area.
<img width="600" alt="image" src="https://user-images.githubusercontent.com/118947090/229062516-45b44b99-69b1-4504-9909-2f652004243c.png">

** your CSS looks good and professional
